### ISSUE TITLE
v1.0.0-beta.5 - Trying to install node-red-node-serialport fails

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#16]
With release `v1.0.0-beta.5`, I'm facing the same error as #1. 

+ Installing `node-red-node-serialport` from **Node-RED-Desktop** results in an error.

```
-----------------------------------------------------------
2019-11-11T08:33:59.487Z Install : node-red-node-serialport 0.8.8

2019-11-11T08:33:59.503Z /Applications/Node-RED-Desktop.app/Contents/Resources/app.asar/node_modules/npm/bin/npm-cli.js install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-serialport@0.8.8
2019-11-11T08:34:05.471Z [err] npm ERR! code EACCES
2019-11-11T08:34:05.472Z [err] npm ERR! syscall unlink
2019-11-11T08:34:05.472Z [err] npm ERR! path /Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile
2019-11-11T08:34:05.472Z [err] npm ERR! errno -13
2019-11-11T08:34:05.473Z [err] npm ERR! Error: EACCES: permission denied, unlink '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile'
2019-11-11T08:34:05.473Z [err] npm ERR!  [OperationalError: EACCES: permission denied, unlink '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile'] {
2019-11-11T08:34:05.473Z [err] npm
2019-11-11T08:34:05.473Z [err]  ERR!   cause: [Error: EACCES: permission denied, unlink '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile'] {
2019-11-11T08:34:05.473Z [err] npm ERR!     errno: -13,
2019-11-11T08:34:05.473Z [err] npm ERR!     code: 'EACCES',
2019-11-11T08:34:05.473Z [err] npm ERR!     syscall: 'unlink',
2019-11-11T08:34:05.473Z [err] npm ERR!     path: '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile'
2019-11-11T08:34:05.473Z [err] npm ERR!   },
2019-11-11T08:34:05.473Z [err] npm ERR!   stack: "Error: EACCES: permission denied, unlink '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile'",
2019-11-11T08:34:05.473Z [err] npm ERR!   errno: -13,
2019-11-11T08:34:05.473Z [err] npm ERR!   code: 'EACCES',
2019-11-11T08:34:05.473Z [err] npm ERR!   syscall: 'unlink',
2019-11-11T08:34:05.473Z [err] npm ERR!   path: '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/.bindings.DELETE/build/Makefile',
2019-11-11T08:34:05.473Z [err] npm ERR!   parent: '.Node-RED-Desktop'
2019-11-11T08:34:05.473Z [err] npm ERR! }
2019-11-11T08:34:05.473Z [err] npm ERR! 
2019-11-11T08:34:05.473Z [err] npm ERR! The operation was rejected by your operating system.
2019-11-11T08:34:05.473Z [err] npm ERR! It is likely you do not have the permissions to access this file as the current user
2019-11-11T08:34:05.473Z [err] npm ERR! 
2019-11-11T08:34:05.473Z [err] npm ERR!
2019-11-11T08:34:05.476Z [err]  If you believe this might be a permissions issue, please double-check the
2019-11-11T08:34:05.476Z [err] npm ERR! permissions of the file and its containing directories, or try running
2019-11-11T08:34:05.476Z [err] npm ERR! the command again as root/Administrator.
2019-11-11T08:34:05.489Z [err] 
2019-11-11T08:34:05.489Z [err] npm ERR! A complete log of this run can be found in:
2019-11-11T08:34:05.489Z [err] npm ERR!
2019-11-11T08:34:05.489Z [err]      /Users/ReiVilo/.npm/_logs/2019-11-11T08_34_05_476Z-debug.log
2019-11-11T08:34:05.499Z rc=243
```

+ Installing `node-red-node-serialport` from command line succeeds...

```
ReiVilo@MacBook .Node-RED-Desktop % sudo npm i node-red-node-serialport
Password:

> @serialport/bindings@2.0.8 install /Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

+ node-red-node-serialport@0.8.8
added 58 packages from 42 contributors, removed 1 package, updated 1 package and audited 471 packages in 2.677s
found 0 vulnerabilities
```

...but the Serial nodes are not available on the palette.

<img width="585" alt="Capture d’écran 2019-11-11 à 09 36 02" src="https://user-images.githubusercontent.com/951776/68572916-e39b4300-0466-11ea-8956-84b3d655d74c.png">

+ So I went for the procedure for rebuilding **Electron** detailed in #1. 

However, it fails with the following message:

```
Last login: Mon Nov 11 09:27:13 on ttys001
ReiVilo@MacBook ~ % cd .Node-RED-Desktop 
ReiVilo@MacBook .Node-RED-Desktop % sudo npm install -g electron-rebuild
Password:
/usr/local/bin/electron-rebuild -> /usr/local/lib/node_modules/electron-rebuild/lib/src/cli.js
+ electron-rebuild@1.8.6
updated 1 package in 3.504s
ReiVilo@MacBook .Node-RED-Desktop % sudo electron-rebuild --version 7.1.1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ReiVilo/.electron-gyp/7.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ReiVilo/.electron-gyp/7.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ReiVilo/.electron-gyp/7.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp:329:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:330:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:378:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.13.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ReiVilo/.electron-gyp/7.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ReiVilo/.electron-gyp/7.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ReiVilo/.electron-gyp/7.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp:329:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:330:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:378:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
    ~~~~~~~~~^~~
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/ReiVilo/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/ReiVilo/.Node-RED-Desktop/node_modules/@serialport/bindings
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/usr/local/lib/node_modules/electron-rebuild/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/usr/local/lib/node_modules/electron-rebuild/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/usr/local/lib/node_modules/electron-rebuild/node_modules/rxjs/internal/Subscriber.js:143:22)
ReiVilo@MacBook .Node-RED-Desktop % 
```

I'm using macOS 10.15.1 _Catalina_.

**Comment by sakazuki** [comment]
This cause is that **[node-red-node-serialport@0.8.8](https://flows.nodered.org/node/node-red-node-serialport)** dependencies on [serialport ^7.1.5](https://github.com/node-red/node-red-nodes/blob/master/io/serialport/package.json#L6).
serialport@7.1.5 does not support electron current version. 

workaround.
 
```
git clone https://github.com/node-red/node-red-nodes.git
cd node-red-nodes/io/serialport/
vi package.json

   "dependencies"  : {
-        "serialport"   : "^7.1.5"
+        "serialport"   : "^8.0.5"

npm install
electron-rebuild --version 7.1.1 
```
launch Node-RED-Desktop
[Tools]-[Add a local node...]
select the above directory **..../node-red-nodes/io/serialport**

Primitively, it is better node-red-node-serialport update the dependencies version.
Please open a issue in the master repository [node-red-nodes](https://github.com/node-red/node-red-nodes/issues)

**Comment by rei-vilo** [comment]
Thank you for the detailed procedure, everything works fine now.

I opened the ticket [node-red-node-serialport and Electron 7.1.1 #603](https://github.com/node-red/node-red-nodes/issues/603).
