### ISSUE TITLE
Auto-update error

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#28]
Calling auto-update from...

<img width="420" alt="Capture 2020-10-20 à 10 59 06" src="https://user-images.githubusercontent.com/951776/96564375-5e015380-12c3-11eb-8fa4-62a2191466d9.png">

... raises an error 

<img width="396" alt="Capture 2020-10-20 à 10 58 08" src="https://user-images.githubusercontent.com/951776/96564388-65c0f800-12c3-11eb-8073-36414a30268e.png">

+ macOS 10.15.7 _Catalina_

**Comment by sakazuki** [comment]
Thank you for your report.
Can you find any additional information about this error in log ?

**Comment by rei-vilo** [comment]
Sure, please find the log file excerpt below.

```
[2020-10-20 22:47:15.315] [info] Found version 1.2.0 (url: Node-RED-Desktop-1.2.0-mac.zip, Node-RED-Desktop-1.2.0.dmg)
[2020-10-20 22:47:15.316] [info] update available 1.2.0
[2020-10-20 22:47:36.652] [info] Checking for update
[2020-10-20 22:47:37.754] [info] Found version 1.2.0 (url: Node-RED-Desktop-1.2.0-mac.zip, Node-RED-Desktop-1.2.0.dmg)
[2020-10-20 22:47:37.755] [info] Downloading update from Node-RED-Desktop-1.2.0-mac.zip, Node-RED-Desktop-1.2.0.dmg
[2020-10-20 22:47:37.963] [error] Error: Error: Cannot download "https://github.com/sakazuki/node-red-desktop/releases/download/v1.2.0/Node-RED-Desktop-1.2.0-mac.zip", status 404: Not Found
    at ClientRequest.<anonymous> (/Users/ReiVilo/Desktop/Node-RED-Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:250:26)
    at ClientRequest.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
[2020-10-20 22:47:37.963] [info] Error in auto-updater. Error: Cannot download "https://github.com/sakazuki/node-red-desktop/releases/download/v1.2.0/Node-RED-Desktop-1.2.0-mac.zip", status 404: Not Found
[2020-10-20 22:47:37.965] [error] Error: Cannot download "https://github.com/sakazuki/node-red-desktop/releases/download/v1.2.0/Node-RED-Desktop-1.2.0-mac.zip", status 404: Not Found
    at ClientRequest.<anonymous> (/Users/ReiVilo/Desktop/Node-RED-Desktop.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/src/httpExecutor.ts:250:26)
    at ClientRequest.emit (events.js:310:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6157)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
```

**Comment by sakazuki** [comment]
I uploaded Node-RED-Desktop-1.2.0-mac.zip and succeeded to download it.
But still it cannot be installed because of the unresolved issue
https://github.com/electron-userland/electron-builder/issues/4299

Now Mac users of Node-RED Desktop cannot use auto-update.
Please update manually with *.dmg file.
