### ISSUE TITLE
Building Node-RED Desktop v1.2.2 on macOS 10.15.7

### ISSUE THREAD

**Issue by rei-vilo** [sakazuki/node-red-desktop#37]
Contrary to previous releases, Node-RED Desktop v1.2.2 isn't available as a binary for macOS. 

* Do you plan to release a binary for macOS?

So I try to build it by myself. I followed the [procedure](https://github.com/sakazuki/node-red-desktop#how-to-build-node-red-desktop) and faced some issues.

```
% npm install
% npm run build

> node-red-desktop@1.2.2 build /Users/USER/Downloads/node-red-desktop-1.2.2
> tsc && node build.js

node_modules/ngrok/ngrok.d.ts:1:66 - error TS7016: Could not find a declaration file for module 'request'. '/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/request/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/request` if it exists or add a new declaration (.d.ts) file containing `declare module 'request';`

1 import { CoreOptions, Request, RequestAPI, RequiredUriUrl } from 'request';
                                                                   ~~~~~~~~~
```

Using the recommended command solved this first issue.

```
% npm i --save-dev @types/request
```

However, building failed with two errors.

```
% npm run build

Error #1 --------------------------------------------------------------------------------
TypeError: Cannot read property 'provider' of null
    at createUpdateInfoTasks (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:110:44)

Error #2 --------------------------------------------------------------------------------
TypeError: Cannot read property 'provider' of null
    at createUpdateInfoTasks (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:110:44)
    at throwError (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/builder-util/src/asyncTaskManager.ts:90:11)
    at checkErrors (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/builder-util/src/asyncTaskManager.ts:53:9)
    at AsyncTaskManager.awaitTasks (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/builder-util/src/asyncTaskManager.ts:58:5)
    at PublishManager.awaitTasks (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/app-builder-lib/src/publish/PublishManager.ts:210:28)
    at /Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/app-builder-lib/src/index.ts:94:32
    at executeFinally (/Users/USER/Downloads/node-red-desktop-1.2.2/node_modules/builder-util/src/promise.ts:25:9)
    at /Users/USER/Downloads/node-red-desktop-1.2.2/build.js:38:17
```

Thank you and best regards,

**Comment by sakazuki** [comment]
Hi @rei-vilo 
Sorry for late response.
I don't encounter the above error.  (I used node v12.13.0 to build)

I will release v1.2.3(Node-RED 1.2.9) with Windows and Mac soon.

**Comment by rei-vilo** [comment]
Thank you! Release v.1.2.3 works fine.
