### ISSUE TITLE
Fail to launch Node-RED-Destkop v2.0.0-beta.1

### ISSUE THREAD

**Issue by sakazuki** [sakazuki/node-red-desktop#49]
Fail to launch v2.0.0-beta.1 

```
[2021-08-10 20:59:39.591] [info]  [
  'C:\\Users\\testuser\\AppData\\Local\\Programs\\node-red-desktop\\Node-RED-Desktop.exe'
]
[2021-08-10 20:59:42.849] [error] TypeError: Cannot read property 'withFileTypes' of null
    at e.readdir (electron/js2c/asar_bundle.js:5:9862)
    at go$readdir (C:\Users\testuser\AppData\Local\Programs\node-red-desktop\resources\app.asar\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:201:14)
    at Object.readdir (C:\Users\testuser\AppData\Local\Programs\node-red-desktop\resources\app.asar\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:198:12)
    at Object.readdir (C:\Users\testuser\AppData\Local\Programs\node-red-desktop\resources\app.asar\node_modules\universalify\index.js:5:57)
    at C:\Users\testuser\AppData\Local\Programs\node-red-desktop\resources\app.asar\node_modules\@node-red\util\lib\i18n.js:53:16
    at new Promise (<anonymous>)
    at C:\Users\testuser\AppData\Local\Programs\node-red-desktop\resources\app.asar\node_modules\@node-red\util\lib\i18n.js:51:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by sakazuki** [comment]
patched v2.0.0-beta.19
